name: eco_gestion
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9
  percent_indicator: ^4.2.3
  image_picker: ^1.0.12
  stylish_bottom_bar: ^1.1.1

  # Firebase Core
  firebase_core: ^3.8.0

  # Firebase Auth
  firebase_auth: ^5.3.3

  # Cloud Firestore
  cloud_firestore: ^5.5.0

  # Firebase Storage
  firebase_storage: ^12.3.6

  # Firebase Messaging
  firebase_messaging: ^15.1.5

  # Firebase Database
  firebase_database: ^11.1.6

  # Firebase App Check
  firebase_app_check: ^0.3.1+6

  # Autres dépendances
  provider: ^6.1.1
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.2
  mqtt_client: ^10.0.0
  intl: ^0.19.0
  flutter_local_notifications: ^16.2.0
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
