name: eco_gestion
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9
  percent_indicator: ^4.2.3
  image_picker: ^1.0.12
  stylish_bottom_bar: ^1.1.1
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0
  firebase_auth_web: ^5.8.13
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.10
  provider: ^6.1.1
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.5
  mqtt_client: ^10.8.0
  intl: ^0.19.0
  firebase_database: ^10.5.7
  firebase_app_check: ^0.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
