// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtJD1o7VhzK05T5DjMTtTDXLMqjBuuGjk',
    appId: '1:1030131641397:android:d98086369b83b2dccc557c',
    messagingSenderId: '1030131641397',
    projectId: 'ecogestionapp',
    databaseURL: 'https://ecogestionapp-default-rtdb.firebaseio.com',
    storageBucket: 'ecogestionapp.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQrGfhKmNKxl5AANXZ-Q92DYH5PJeQSuA',
    appId: '1:1030131641397:web:2cf6e988cc23573bcc557c',
    messagingSenderId: '1030131641397',
    projectId: 'ecogestionapp',
    authDomain: 'ecogestionapp.firebaseapp.com',
    databaseURL: 'https://ecogestionapp-default-rtdb.firebaseio.com',
    storageBucket: 'ecogestionapp.firebasestorage.app',
  );

}